version: '3.9'
services:
  drupal:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html
      - ./apache/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10.3
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - 9090:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
    restart: always
